---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: project-admin-role
rules:
  - apiGroups: ["*"] 
    resources: ["*"]
    verbs: ["*"]     
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-admin-rolebinding
  namespace: roboshop
subjects:
- kind: User
  name: project-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: project-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader
rules:
- apiGroups: [""]
  resources: ["deployments","nodes","namespaces","services"]
  verbs: ["get", "watch", "list"] 
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: cluster-reader-role-binding
subjects:
- kind: User
  name: project-admin # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io 
