apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::464117734641:role/eksctl-cluster123-nodegroup-clust-NodeInstanceRole-1DI3BMSQPXQUS
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - usersarn: arn:arn:aws:iam::464117734641:user/k8-project
      username: k8-project    
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-14T08:39:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1072"
  uid: eafd7e2e-4473-4d5e-9880-dd8ba5fcc132