apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::464117734641:role/eksctl-eks-cluster-nodegroup-eks-NodeInstanceRole-171EY1QQKUZEO
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - usersarn: arn:aws:iam::464117734641:user/roboshop-admin
      username: roboshop-admin    
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-12T07:28:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1138"
  uid: 9b3ce855-b5df-4db4-982e-571f05ee30f0