apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::464117734641:role/eksctl-cluster123-nodegroup-clust-NodeInstanceRole-1XYYMEHN99GZM
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - usersarn: arn:aws:iam::464117734641:user/roboshop-admin
      username: roboshop-admin    
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-16T13:26:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1081"
  uid: c57968d7-9915-4221-afde-c6653c43a9bf