apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::464117734641:role/eksctl-eks-cluster-nodegroup-eks-NodeInstanceRole-1R749NVSCNE2T
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - usersarn: arn:aws:iam::464117734641:user/roboshop-admin
      username: roboshop-admin    
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-11T18:13:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1113"
  uid: 17480f2f-245d-41d9-a4ad-f106dc7810d0